export const MAX_FILES = 100;

export const STORAGE_CONSTANTS = {
  BUCKET_NAME: process.env.STORAGE_BUCKET_NAME ?? 'tcx-transcripts-dev',
  SIGNED_URL_EXPIRY: 60 * 15,
};

export const AUDIO_EXTENSIONS = ['.mp3', '.wav', '.aac', '.flac', '.ogg'];
export const AUDIO_MIME_PREFIXES = ['audio/'];

export const JOB_TYPES = {
  IVR: 'IVR',
  CONVERSATIONAL: 'CONVERSATIONAL',
} as const;

const dsBaseUrl =
  process.env.DS_BASE_URL ?? 'http://10.90.114.99:3002/agent-builder/v1';
const dsIvrBaseUrl =
  process.env.DS_IVR_BASE_URL ??
  'https://whisperstream.exlservice.com/agent-builder/v1';
const qaBaseUrl =
  process.env.QA_BASE_URL ?? 'http://10.90.126.167:5123/cx-agentic-eval';
const dsAgenticBaseUrl =
  process.env.DS_AGENTIC_BASE_URL ??
  'https://whisperstream.exlservice.com/cx-autonomous-agents/v1';

export const DS_API_ENDPOINTS = {
  INTENT_ANALYSIS: `${dsBaseUrl}/start-job-intent-analysis`,
  INTENT_CLUSTERING: `${dsBaseUrl}/start-job-cluster-analysis`,
  PROCESS_MAP: `${dsBaseUrl}/start-job-process-map`,
  AGENTIC_GENERATION: `${dsBaseUrl}/start-job-agent-builder`,
  EXPRESS_MODE: `${dsBaseUrl}/Expressmode`,
  IVR_VALIDATION: `${dsIvrBaseUrl}/ivrvalidation`,
  INTENT_ANALYSIS_IVR: `${dsIvrBaseUrl}/start-job-intent-analysisIVR2PM`,
  PROCESS_MAP_IVR: `${dsIvrBaseUrl}/start-job-process-mapIVR2PM`,
  UML_GENERATION: `${dsAgenticBaseUrl}/get_run_uml`,
  API_GENERATION: `${dsAgenticBaseUrl}/get_run_api_gen`,
  BLUEPRINT_GENERATION: `${dsAgenticBaseUrl}/get_run_blueprint`,
  BUILD_DEPLOY_AGENT: `${dsAgenticBaseUrl}/get_build_and_deploy`,
  CHECK_STATUS: `${dsAgenticBaseUrl}/process_status`,
  GENERATE_SCENARIO: `${qaBaseUrl}/generate_scenario`,
  PROCESS_SCENARIO: `${qaBaseUrl}/process_scenario`,
  GOALS_ENTITIES: `${qaBaseUrl}/get_goals_entities`,
};

export const JOB_STATUS_ORDER: Record<string, number> = {
  PENDING_UPLOAD: 0,
  FILE_UPLOADED: 1,
  INTENT_ANALYSIS_PENDING: 2,
  INTENT_ANALYSIS_COMPLETED: 3,
  INTENT_CLUSTERING_PENDING: 4,
  INTENT_CLUSTERING_COMPLETED: 5,
  PROCESS_FLOW_GENERATION_PENDING: 6,
  PROCESS_FLOW_GENERATION_COMPLETED: 7,
  PROCESS_MERGE_PENDING: 8,
  PROCESS_MERGE_COMPLETED: 9,
  UML_GENERATION_PENDING: 10,
  UML_GENERATION_COMPLETED: 11,
  AGENTIC_API_GENERATION_PENDING: 12,
  AGENTIC_API_GENERATION_COMPLETED: 13,
  AGENTIC_JSON_GENERATION_PENDING: 14,
  AGENTIC_JSON_GENERATION_COMPLETED: 15,
  BUILD_DEPLOY_AGENT_PENDING: 16,
  BUILD_DEPLOY_AGENT_COMPLETED: 17,
  DONE: 18,
};

export const JOB_STATUS = {
  PENDING_UPLOAD: 'PENDING_UPLOAD',
  UPLOADED: 'FILE_UPLOADED',
  INTENT_ANALYSIS_PENDING: 'INTENT_ANALYSIS_PENDING',
  INTENT_ANALYSIS_COMPLETED: 'INTENT_ANALYSIS_COMPLETED',
  INTENT_CLUSTERING_PENDING: 'INTENT_CLUSTERING_PENDING',
  INTENT_CLUSTERING_COMPLETED: 'INTENT_CLUSTERING_COMPLETED',
  PROCESS_FLOW_GENERATION_PENDING: 'PROCESS_FLOW_GENERATION_PENDING',
  PROCESS_FLOW_GENERATION_COMPLETED: 'PROCESS_FLOW_GENERATION_COMPLETED',
  PROCESS_MERGE_PENDING: 'PROCESS_MERGE_PENDING',
  PROCESS_MERGE_COMPLETED: 'PROCESS_MERGE_COMPLETED',
  SME_VALIDATION_PENDING: 'SME_VALIDATION_PENDING',
  UML_GENERATION_PENDING: 'UML_GENERATION_PENDING',
  UML_GENERATION_COMPLETED: 'UML_GENERATION_COMPLETED',
  AGENTIC_API_GENERATION_PENDING: 'AGENTIC_API_GENERATION_PENDING',
  AGENTIC_API_GENERATION_COMPLETED: 'AGENTIC_API_GENERATION_COMPLETED',
  AGENTIC_JSON_GENERATION_PENDING: 'AGENTIC_JSON_GENERATION_PENDING',
  AGENTIC_JSON_GENERATION_COMPLETED: 'AGENTIC_JSON_GENERATION_COMPLETED',
  BUILD_DEPLOY_AGENT_PENDING: 'BUILD_DEPLOY_AGENT_PENDING',
  BUILD_DEPLOY_AGENT_COMPLETED: 'BUILD_DEPLOY_AGENT_COMPLETED',
  DONE: 'DONE',
  ERROR: 'ERROR',
  CREATED: 'CREATED',
} as const;

export const expectedPreviousStatus: Record<string, string> = {
  [JOB_STATUS.INTENT_ANALYSIS_PENDING]: JOB_STATUS.UPLOADED,
  [JOB_STATUS.INTENT_CLUSTERING_PENDING]:
    JOB_STATUS.INTENT_ANALYSIS_COMPLETED,
  [JOB_STATUS.PROCESS_FLOW_GENERATION_PENDING]:
    JOB_STATUS.INTENT_CLUSTERING_COMPLETED,
  [JOB_STATUS.UML_GENERATION_PENDING]: JOB_STATUS.PROCESS_MERGE_COMPLETED,
  [JOB_STATUS.AGENTIC_API_GENERATION_PENDING]:
    JOB_STATUS.UML_GENERATION_COMPLETED,
  [JOB_STATUS.AGENTIC_JSON_GENERATION_PENDING]:
    JOB_STATUS.AGENTIC_API_GENERATION_COMPLETED,
  [JOB_STATUS.BUILD_DEPLOY_AGENT_PENDING]:
    JOB_STATUS.AGENTIC_JSON_GENERATION_COMPLETED,
  [JOB_STATUS.DONE]: JOB_STATUS.BUILD_DEPLOY_AGENT_COMPLETED,
};

export const expectedPreviousIVRStatus: Record<string, string> = {
  [JOB_STATUS.INTENT_ANALYSIS_PENDING]: JOB_STATUS.UPLOADED,
  [JOB_STATUS.PROCESS_FLOW_GENERATION_PENDING]:
    JOB_STATUS.INTENT_ANALYSIS_COMPLETED,
  [JOB_STATUS.AGENTIC_JSON_GENERATION_PENDING]:
    JOB_STATUS.PROCESS_MERGE_COMPLETED,
  [JOB_STATUS.AGENTIC_JSON_GENERATION_COMPLETED]: JOB_STATUS.DONE,
};

export const LOG_EVENTS = {
  CREATE_JOB: 'CREATE_JOB',
  TRANSCRIPTS_PROCESSING: 'TRANSCRIPTS_PROCESSING',
  TRANSCRIPTS_PROCESSED: 'TRANSCRIPTS_PROCESSED',
  FILE_PROCESSING: 'Processing',
  FILE_PROCESSED: 'Success',
  PENDING_UPLOAD: 'PENDING_UPLOAD',
  UPLOADED: 'FILE_UPLOADED',
  INTENT_ANALYSIS_PENDING: 'INTENT_ANALYSIS_PENDING',
  INTENT_ANALYSIS_COMPLETED: 'INTENT_ANALYSIS_COMPLETED',
  INTENT_CLUSTERING_PENDING: 'INTENT_CLUSTERING_PENDING',
  INTENT_CLUSTERING_COMPLETED: 'INTENT_CLUSTERING_COMPLETED',
  PROCESS_FLOW_GENERATION_PENDING: 'PROCESS_FLOW_GENERATION_PENDING',
  PROCESS_FLOW_GENERATION_COMPLETED: 'PROCESS_FLOW_GENERATION_COMPLETED',
  PROCESS_MERGE_PENDING: 'PROCESS_MERGE_PENDING',
  PROCESS_MERGE_COMPLETED: 'PROCESS_MERGE_COMPLETED',
  SME_VALIDATION_PENDING: 'SME_VALIDATION_PENDING',
  AGENTIC_JSON_GENERATION_PENDING: 'AGENTIC_JSON_GENERATION_PENDING',
  AGENTIC_JSON_GENERATION_COMPLETED: 'AGENTIC_JSON_GENERATION_COMPLETED',
} as const;

export const MIME_TYPE: Record<string, string> = {
  txt: 'text/plain',
  csv: 'text/csv',
  json: 'application/json',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  png: 'image/png',
  pdf: 'application/pdf',
  doc: 'application/msword',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xls: 'application/vnd.ms-excel',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  wav: 'audio/wav',
  mp3: 'audio/mpeg',
  mp4: 'audio/mp4',
  m4a: 'audio/mp4',
  aac: 'audio/aac',
  flac: 'audio/flac',
  ogg: 'audio/ogg',
  wma: 'audio/x-ms-wma',
  zip: 'application/zip',
};

export const DEFAULT_ALLOWED_ORIGINS = [
  'https://cxaa-dev.exlservice.com',
  'https://cx-apps.exlservice.com',
  'http://localhost:5000',
];
